#!/bin/bash

# Update and upgrade the system
apt update && apt upgrade -y && apt full-upgrade -y && apt install curl socat -y
sudo apt update -q && sudo apt install -y sudo wget

# Run block-iran.sh script
yes | bash <(curl -Ls https://raw.githubusercontent.com/KhosroNet/Ssh-User-management/main/block-iran.sh --ipv4)

# Configure cache clearing cron job
echo "*/45 * * * * root sync; echo 1 > /proc/sys/vm/drop_caches; sync; echo 2 > /proc/sys/vm/drop_caches; sync; echo 3 > /proc/sys/vm/drop_caches" >> /etc/crontab

# Apply the cron configuration
crontab /etc/crontab

# Linux Optimizer
wget "https://raw.githubusercontent.com/hawshemi/Linux-Optimizer/main/linux-optimizer.sh" -O linux-optimizer.sh && chmod +x linux-optimizer.sh && bash linux-optimizer.sh 
